### PR TITLE
fix: updates for tflint

### PR DESCRIPTION
**Pull request by apeabody**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_tflint
 Failed TFlint check. More details below. 
 ```bash 
Checking for tflint
Working in . ...
2 issue(s) found:
Warning: local.is_static_zone is declared but not used (terraform_unused_declarations)
  on main.tf line 18:
  18:   is_static_zone = var.type == "public" || var.type == "private"
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_unused_declarations.md
Warning: `target_network` variable has no type (terraform_typed_variables)
  on variables.tf line 48:
  48: variable "target_network" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_typed_variables.md
tflint failed . 
Working in ./examples/forwarding-zone ...
tflint passed ./examples/forwarding-zone 
Working in ./examples/peering-zone ...
tflint passed ./examples/peering-zone 
Working in ./examples/private-zone ...
tflint passed ./examples/private-zone 
Working in ./examples/public-zone ...
tflint passed ./examples/public-zone 
Skipping ./test/fixtures/private_zone
Skipping ./test/fixtures/public_zone
Skipping ./test/setup
 ```

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks @apeabody!!

**Pull request merged**
