### PR TITLE
feat: add reverse lookup & service dir zone

### PR DESCRIPTION
**Pull request by nikhilmakhijani**
Adding reverse_lookup and service directory zone creation.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
Checking for missing newline at end of file
Error: No newline at end of file ./outputs.tf
 ```

**Comment by nikhilmakhijani** [comment]
@morgante @bharathkkb please review.

**Comment by nikhilmakhijani** [comment]
@bharathkkb  Please review.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @nikhilmakhijani and sorry for the delay

**Pull request merged**
